services:
  nginx:
    image: nginx:1.26.0-alpine
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      backend:
        condition: service_started
      client:
        condition: service_started
    networks:
      - internal
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend:1.0.0
    networks:
      - internal

  client:
    build:
      context: client
      dockerfile: Dockerfile
    image: client:1.0.0
    networks:
      - internal

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: monmotdepasse
      POSTGRES_DB: todosdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge