services:
  nginx:
    image: nginx:1.26.0-alpine
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - client
    networks:
      - internal
  
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    image: backend-dev:1.0.0
    volumes:
      - "${PWD}/backend/todos:/app/todos"
    networks:
      - internal
    depends_on:
      - db
      
  client:
    image: node:20.19.3
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host"
    volumes:
      - "${PWD}/client:/app"
    networks:
      - internal

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: monmotdepasse
      POSTGRES_DB: todosdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge 